### ISSUE TITLE
[Bug] newest version not found when integrating as custom component in HA

### ISSUE THREAD

**Issue by rine77** [EdupageAPI/edupage-api#76]
**Describe the bug**
I understand the newest version is  0.10.8, so I played around a bit and found that when using "requirements" in  Home Assistant custom component manifest.json (I'm creating a HA EduPage integration based on your library) the last number HA finds is "0.10.6":

**Your code**
manifest.json
    "requirements": ["edupage_api==0.10.8"],

**Error message**
Unable to install package edupage_api==0.10.8: ERROR: Could not find a version that satisfies the requirement edupage_api==0.10.8 (from versions: 0.1, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.9.81, 0.9.82, 0.9.83, 0.9.84, 0.9.85, 0.9.86, 0.9.87, 0.9.91, 0.9.92, 0.9.94, 0.9.95, 0.9.96, 0.9.97, 0.9.98, 0.9.981, 0.9.982, 0.9.983, 0.9.984, 0.9.985, 0.9.986, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.5, 0.10.6) ERROR: No matching distribution found for edupage_api==0.10.8

**Expected behavior**
I was expecting it finds 0.10.8 

**Version**
- Edupage API version: **0.10.8**

**Comment by ivanhrabcak** [comment]
While you use `edupage_api` in imports, the package name when installing is `edupage-api`.

**Comment by ivanhrabcak** [comment]
[0.10.8 is now available on PyPi.](https://pypi.org/project/edupage-api/0.10.8/)

**Comment by rine77** [comment]
Awesome - thanks!
I dont know if you know Homeassistant but integrating your library into HA gives people some nice possibilities, so I started this.

**Comment by rine77** [comment]
works, thanks
