### ISSUE TITLE
Automatic Lunch Ordering

### ISSUE THREAD

**Issue by HereGrain** [EdupageAPI/edupage-api#78]
An algorithm that will automatically order lunches so that all students have lunch (most usefull for those who always forget)

Possible ticking of boxes with preferences, and then if lunch ordering is available it will order it. Before ordering though you can check it to see if its alright.

**Comment by BelKed** [comment]
Thank you for your thoughtful suggestion about automating lunch ordering :) While we won't be adding this feature directly to the library, we appreciate your idea to help students who often forget to order. The good news is that our library already supports lunch ordering, so you have a solid foundation to work from.

For automation, you may want to consider using tools such as **cron** to set up a custom solution that meets your specific needs. This approach allows for more flexibility while keeping our library focused. If you need guidance on setting up such automation, feel free to ask for advice in our [Discord](https://discord.gg/fg6zBu9ZAn) :)
