### ISSUE TITLE
ImportError: cannot import name 'BadCredentialsException' from 'edupage_api'

### ISSUE THREAD

**Issue by Grilioni** [EdupageAPI/edupage-api#80]
Hey bro! I get this:   from edupage_api import Edupage, BadCredentialsException, LoginDataParsingException
ImportError: cannot import name 'BadCredentialsException' from 'edupage_api'  when trying to login. what to do?

**Comment by BelKed** [comment]
You should do it like this:

```py
from edupage_api import Edupage
from edupage_api.exceptions import BadCredentialsException, LoginDataParsingException
```

I just can't find `LoginDataParsingException` anywhere in the code... So correctly we shouldn't even import that:

```py
from edupage_api import Edupage
from edupage_api.exceptions import BadCredentialsException
```

**Comment by BelKed** [comment]
As I'm searching through the commit history, `LoginDataParsingException` has been removed in https://github.com/EdupageAPI/edupage-api/pull/31. I'll update the `README.md` to aviod further confusion :)

**Comment by Grilioni** [comment]
Ohhh, okaay. Thank you

kind regards,
Grigorii Bilibin

**Comment by Grilioni** [comment]
Thanks man;) I’ll keep contact w/ u

kind regards,
Grigorii Bilibin

**Comment by Grilioni** [comment]
Yes, sry. Forgot bout that

kind regards,
Grigorii Bilibin
